### ISSUE TITLE
Advanced Columns not showing correctly in Editor anymore

### ISSUE THREAD

**Issue by Veltro** [brainstormforce/ultimate-addons-for-gutenberg#153]
The advanced columns began to appear one below the other in the Wordpress Editor and not the correct way that one column is next to each other as of 2 days ago.

Please fix this soon as it is very difficult to maintain the site with this bug.
Thanks.

**Comment by jamiemarsland** [comment]
We see this too. To clarify it only happens when the Gutenberg 7.2.0 plugin is installed.

**Comment by Veltro** [comment]
> 
> 
> We see this too. To clarify it only happens when the Gutenberg 7.2.0 plugin is installed.

Can I downgrade the Gutenberg to the previous version then until they fix it? Cause I really need this plugin.

**Comment by Veltro** [comment]
> 
> 
> @Veltro - Please add a support request [here](https://ultimategutenberg.com/support). I will share a development version with you.

Just sent the ticket, thanks.

**Comment by nicholasurban** [comment]
I see the same thing. Unfortunate.

**Comment by Veltro** [comment]
> 
> 
> @Veltro - Please add a support request [here](https://ultimategutenberg.com/support). I will share a development version with you.

Any fix? 1 month since the problem was reported, I've sent the ticket as request and not a single response or fix.

**Comment by vrundakansara** [comment]
@Veltro Do you mind sharing the ticket ID with us?
Anyway, this has already been fixed in this PR here - #156

**Comment by Veltro** [comment]
Thanks for answering @vrundakansara but it's not fixed yet.
I am using the latest versions of both Gutenberg(7.5) and Ultimate addons(1.14.6).
I can only use Advanced columns rolling back Gutenberg to 7.1, if not my editor is screwed-up like this:
![image](https://user-images.githubusercontent.com/7377006/74467206-632a1b00-4e77-11ea-9b62-22f14a228e73.png)

Look at the diference using Gutenberg 7.1:
![image](https://user-images.githubusercontent.com/7377006/74467343-a1273f00-4e77-11ea-8f09-423db0c0200f.png)

I hope you guys can really fix this, it's the feature I use the most. :S

**Comment by vrundakansara** [comment]
@Veltro - Yes, the shown issue will be fixed once we release the update.
You can reach us out [here](https://www.ultimategutenberg.com/support/) is you need a development version for the fix.

**Comment by vrundakansara** [comment]
Fixed - #157
